sudo: required
services:
    - docker


before_install:
    - docker build -t gaurav/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gaurav/react-test npm test

after_success:
    - docker build -t gaurav/complex-client ./client
    - docker build -t gaurav/complex-server ./server
    - docker build -t gaurav/complex-worker ./worker
    - docker build -t gaurav/complex-nginx ./nginx
    #LOGIN in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push the images to Docker HUB
    - docker push gaurav/complex-client
    - docker push gaurav/complex-server
    - docker push gaurav/complex-worker
    - docker push gaurav/complex-nginx