sudo: required
services:
    - docker


before_install:
    - docker build -t gauravsahni25/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gauravsahni25/react-test npm test

after_success:
    - docker build -t gauravsahni25/complex-client ./client
    - docker build -t gauravsahni25/complex-server ./server
    - docker build -t gauravsahni25/complex-worker ./worker
    - docker build -t gauravsahni25/complex-nginx ./nginx
    #LOGIN in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push the images to Docker HUB
    - docker push gauravsahni25/complex-client
    - docker push gauravsahni25/complex-server
    - docker push gauravsahni25/complex-worker
    - docker push gauravsahni25/complex-nginx

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "DockerComplex"
    env: "Dockercomplex-env"
    bucket_name: "elasticbeanstalk-us-east-2-188413114508"
    bucket_path: "docker-complex"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY